sudo: false
language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
before_script: 
 - npm install -g istanbul
 - npm install -g codeclimate-test-reporter
script: istanbul cover -v test/run.js 
after_script:
 - codeclimate-test-reporter < coverage/lcov.info
env: 
 - CODECLIMATE_REPO_TOKEN=
