sudo: false
language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
before_script: 
 - npm install -g istanbul
script: istanbul cover -v test/run.js 
after_success:
 - npm install -g codeclimate-test-reporter
 - codeclimate-test-reporter < coverage/lcov.info
env: 
 - CODECLIMATE_REPO_TOKEN=cbe8daec45894755461b477b6372f3e35296fef3838d5d5df82bec8de67d63d8
 - NODE_ENV=test
notifications:
  email: false